Add unit tests for handling invalid LiteDB files
litedb-org/LiteDB pull request #2507
Opened 2024-06-12 07:18 UTC by PanWuming

### Description

This PR adds two unit tests to handle scenarios where LiteDB attempts to open invalid database files:
- **Test_AddDatabase_InvalidDatabase**: Tests handling of a file with invalid content.
- **Test_AddDatabase_InvalidDatabase_LargeFile**: Tests handling of a file with invalid content larger than 16KB.

### Issues

These tests are intended to address issue #2501.

### Bugs Discovered

1. **Test_AddDatabase_InvalidDatabase**:
   - **Bug**: The test expected a `LiteDB.LiteException` to be thrown.
   - **Actual**: No exception was thrown.
   - **Details**:
     ```
     Assert.Throws() Failure
     Expected: typeof(LiteDB.LiteException)
     Actual:   (No exception was thrown)
        at LiteDB.Tests.Database.InvalidFile_Tests.Test_AddDatabase_InvalidDatabase() in /Users/panwuming/Code/GitHub/LiteDB/LiteDB.Tests/Database/InvalidFile_Tests.cs:line 30
     ```

2. **Test_AddDatabase_InvalidDatabase_LargeFile**:
   - **Bug**: The test expected a `LiteDB.LiteException` to be thrown.
   - **Actual**: A `System.ArgumentOutOfRangeException` was thrown.
   - **Details**:
     ```
     Assert.Throws() Failure
     Expected: typeof(LiteDB.LiteException)
     Actual:   typeof(System.ArgumentOutOfRangeException): Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')
     ```

These findings indicate that LiteDB is not handling invalid files as expected, leading to different types of exceptions or no exceptions at all.

2024-06-12 07:50 UTC, JKamsker commented
Does it also work with memorystreams? I prefer not to write on my disk.

2024-06-12 08:34 UTC, PanWuming commented
> Does it also work with memorystreams? I prefer not to write on my disk.

Thank you for your feedback. I have updated the PR with the requested MemoryStream tests and included exception outputs for debugging. Please review the latest changes.

2024-06-19 17:41 UTC, mbdavid approved these changes
Thanks!

2024-09-11 04:39 UTC, yz5548 approved these changes

2026-09-13 12:37 UTC, JKamsker requested changes
Merge-readiness update for `b1724014dc79`.

Changes needed before merge:

- Pair the regression tests with the behavior fixes they require, or keep this as a draft reproduction PR until those fixes are ready. All four added tests failed in the latest focused rerun against dev `a1612908` after retargeting; that evidence should not be presented as a passing suite on today's target.
- Define the invalid-file exception contract and implement it consistently for files and streams, without accepting invalid data or losing the original failure during cleanup.
- Replace fixed filenames with unique temporary paths and put cleanup in finally blocks so failed assertions do not leave files behind or collide with other tests. Preserve useful file and MemoryStream coverage.
- Revalidate the complete added suite against the latest dev, including the merged .NET 10 target, before requesting a merge.

2026-09-13 21:36 UTC, JKamsker commented
Addressed the requested changes in `d744bec5`:

- merged the latest `dev` into the contributor branch
- made file/stream length inspection non-mutating and defer torn-page trimming until after header validation
- return `LiteException.INVALID_DATABASE` consistently for invalid short, page-sized, and >16 KB file/stream inputs
- preserve invalid files/streams byte-for-byte, including read-only and legacy-without-upgrade cases
- replaced fixed test filenames with unique temporary paths and `finally` cleanup
- retained recovery coverage for genuine databases with torn trailing pages

Validation:
- `dotnet build LiteDB.sln -c Release -p:TestingEnabled=true --no-restore`
- focused invalid/stream/crypto/upgrade suites on `net8.0` and `net10.0` (35/35 passed per target before the final focused rebuild rerun; final invalid/rebuild/upgrade rerun: 21 passed, 1 skipped)
- full LiteDB tests on `net8.0`: 876 passed, 7 skipped
- full LiteDB tests on `net10.0`: 876 passed, 7 skipped
- `python3 scripts/check-csharp-size.py --base origin/dev`
- `python3 scripts/test-vector-compatibility.py`

2026-09-13 21:46 UTC, JKamsker approved these changes
All requested changes are addressed on `d744bec5`. Invalid files and streams now fail consistently without mutation, cleanup is collision-safe, torn-page recovery remains covered, and the full 45-job CI matrix passes.

2026-09-13 21:46 UTC, JKamsker commented
CI follow-up: [run 34784324255](https://github.com/litedb-org/LiteDB/actions/runs/34784324255) completed successfully with all 45 jobs passing on `d744bec5`.

2026-09-16 23:01 UTC, merged